package cs2030.simulator;

import java.util.LinkedList;
import cs2030.simulator.RandomGenerator;
import cs2030.simulator.Customer;

/**
 * Encapsulates a list of customers and an array of service time.
 * customers and service time are generated by a randomgenerator
 */
public class RandomCustomers {
    public LinkedList<Customer> customers = new LinkedList<>();
    public double[] serviceTime;

    /**
     * Constructs class RandomCustomers.
     * @param numOfCustomers the length of customers and service time
     * @param seed seed of RandomGenerator
     * @param lambda lambda of RandomGenerator
     * @param mu mu of RandomGenerator
     */
    public RandomCustomers(int numOfCustomers, int seed, double lambda, double mu) {
        double thisArrivalTime = 0;
        this.serviceTime = new double[numOfCustomers];
        RandomGenerator rg = new RandomGenerator(seed, lambda, mu);
        for (int i = 0; i < numOfCustomers; i++) {
            Customer newCustomer;
            if (i == 0) {
                newCustomer = new Customer(thisArrivalTime, i + 1);
            } else {
                thisArrivalTime += rg.genInterArrivalTime​();
                newCustomer = new Customer(thisArrivalTime, i + 1);
            }
            this.customers.add(newCustomer);
            this.serviceTime[i] = rg.genServiceTime​();
        }
    }
}
